apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: ocp4-cis-node-managed-openshift
spec:
  extends: ocp4-cis-node
  description: OCP4 CIS Node profile
  title: OCP4 CIS Node profile, modified to remove controls that would take a managed service out of support.
  disableRules:
  - name: ocp4-kubelet-enable-protect-kernel-defaults
    rationale: Kubelet modification not allowed for managed service. https://learn.microsoft.com/en-us/azure/openshift/support-policies-v4#cluster-configuration-requirements
  - name: ocp4-kubelet-enable-protect-kernel-sysctl
    rationale: Kubelet modification not allowed for managed service. https://learn.microsoft.com/en-us/azure/openshift/support-policies-v4#cluster-configuration-requirements
