apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: ocp4-cis-managed-openshift
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: TailoredProfile
    name: ocp4-cis-managed-openshift
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: TailoredProfile
    name: ocp4-cis-node-managed-openshift
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: default